# Generated by Django 3.1.6 on 2021-02-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('hsn', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('store_id', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=150)),
            ],
        ),
    ]
