# Generated by Django 3.1.6 on 2021-02-19 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('logo', models.TextField()),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('pincode', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('gst_number', models.CharField(max_length=150)),
                ('gst_type', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('hsn', models.CharField(blank=True, max_length=150, null=True)),
                ('base_price', models.FloatField()),
                ('sales_price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('store_id', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=150)),
                ('comapny_address', models.CharField(max_length=150)),
                ('company_city', models.CharField(max_length=150)),
                ('company_location', models.CharField(max_length=150)),
                ('company_pin', models.CharField(max_length=150)),
                ('company_district', models.CharField(max_length=150)),
                ('company_state', models.CharField(max_length=150)),
                ('company_gstin', models.CharField(max_length=150)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=150)),
                ('company_logo', models.TextField()),
                ('due_amount', models.FloatField()),
                ('sgst', models.FloatField()),
                ('cgst', models.FloatField()),
                ('status', models.BooleanField()),
                ('invoice_type', models.CharField(max_length=150)),
                ('digital_signature', models.CharField(max_length=150)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='invoice.customer')),
                ('product_list', models.ManyToManyField(related_name='orderitems', to='invoice.OrderItems')),
            ],
        ),
    ]
