# Generated by Django 3.1.6 on 2021-02-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='price',
            new_name='base_price',
        ),
        migrations.AddField(
            model_name='inventory',
            name='sales_price',
            field=models.FloatField(default=250.0),
            preserve_default=False,
        ),
    ]
