# Generated by Django 3.1.6 on 2021-02-13 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20210212_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
