# Generated by Django 3.1.6 on 2021-02-13 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_inventory_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
