# Generated by Django 3.1.6 on 2021-02-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20210223_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compony',
            old_name='compony_name',
            new_name='company_name',
        ),
        migrations.AlterField(
            model_name='compony',
            name='company_id',
            field=models.CharField(default='56bb0d44', max_length=150),
        ),
        migrations.AlterField(
            model_name='compony',
            name='company_signature',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='hsn_user_id',
            field=models.CharField(default='64bd0427', max_length=150),
        ),
    ]
