# Generated by Django 3.1.6 on 2021-02-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20210225_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='compony_id',
            field=models.CharField(default='Sdff', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compony',
            name='company_id',
            field=models.CharField(default='3049feb2', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='d939afc3', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='hsn_user_id',
            field=models.CharField(default='d18de87c', max_length=150),
        ),
    ]
