# Generated by Django 3.1.6 on 2021-02-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20210224_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.TextField(default='fsdsf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compony',
            name='company_id',
            field=models.CharField(default='a156fade', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='cf6ae947', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='hsn_user_id',
            field=models.CharField(default='3cb912fa', max_length=150),
        ),
    ]
