# Generated by Django 3.1.6 on 2021-02-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20210223_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compony',
            name='id',
        ),
        migrations.AlterField(
            model_name='compony',
            name='company_id',
            field=models.CharField(default='95089ee2', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='hsn_user_id',
            field=models.CharField(default='58a444e7', max_length=150),
        ),
    ]
