# Generated by Django 3.1.6 on 2021-02-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20210225_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='compony_id',
            new_name='company_id',
        ),
        migrations.AlterField(
            model_name='compony',
            name='company_id',
            field=models.CharField(default='882ad682', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='faa20153', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='hsn_user_id',
            field=models.CharField(default='014cf9ed', max_length=150),
        ),
    ]
