# Generated by Django 3.1.6 on 2021-02-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
