# Generated by Django 3.1.6 on 2021-02-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20210224_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='store_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='compony',
            name='company_id',
            field=models.CharField(default='688b009d', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='a35535bd', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='hsn_user_id',
            field=models.CharField(default='1d910c7a', max_length=150),
        ),
    ]
