# Generated by Django 3.1.6 on 2021-02-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20210216_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
