# Generated by Django 3.1.6 on 2021-02-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20210217_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.TextField(default='Sdf'),
            preserve_default=False,
        ),
    ]
