# Generated by Django 3.1.6 on 2021-02-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20210225_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='comapny_address',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='company_satate',
            new_name='company_state',
        ),
        migrations.AlterField(
            model_name='compony',
            name='company_id',
            field=models.CharField(default='2e92373f', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='31ee33ce', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='hsn_user_id',
            field=models.CharField(default='a4a90f3d', max_length=150),
        ),
    ]
