# Generated by Django 3.1.6 on 2021-02-18 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20210217_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=150)),
                ('comapny_address', models.CharField(max_length=150)),
                ('company_city', models.CharField(max_length=150)),
                ('company_location', models.CharField(max_length=150)),
                ('company_pin', models.CharField(max_length=150)),
                ('company_district', models.CharField(max_length=150)),
                ('company_state', models.CharField(max_length=150)),
                ('company_gstin', models.CharField(max_length=150)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=150)),
                ('company_logo', models.TextField()),
                ('due_amount', models.FloatField()),
                ('sgst', models.FloatField()),
                ('cgst', models.FloatField()),
                ('status', models.BooleanField()),
                ('invoice_type', models.CharField(max_length=150)),
                ('digital_signature', models.CharField(max_length=150)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_name', to='invoice.customer')),
                ('product_list', models.ManyToManyField(related_name='product_list', to='invoice.Inventory')),
            ],
        ),
    ]
