# Generated by Django 3.1.6 on 2021-02-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20210227_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compony',
            old_name='comapny_address',
            new_name='company_address',
        ),
        migrations.AlterField(
            model_name='compony',
            name='company_id',
            field=models.CharField(default='ea0c79d3', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='9c604eb6', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='hsn_user_id',
            field=models.CharField(default='3f665939', max_length=150),
        ),
    ]
