# Generated by Django 3.1.6 on 2021-02-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20210227_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compony',
            name='company_id',
            field=models.CharField(default='bd9be2d3', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='858c18f8', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='hsn_user_id',
            field=models.CharField(default='dae75c70', max_length=150),
        ),
    ]
