# Generated by Django 3.1.6 on 2021-02-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_auto_20210227_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='store_id',
        ),
        migrations.AlterField(
            model_name='compony',
            name='company_id',
            field=models.CharField(default='8cf0005b', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='6dd90d1b', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='hsn_user_id',
            field=models.CharField(default='d9f69dd1', max_length=150),
        ),
    ]
