# Generated by Django 3.1.6 on 2021-02-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_auto_20210227_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxgroup',
            old_name='hsn_sess',
            new_name='hsn_cess',
        ),
        migrations.AlterField(
            model_name='compony',
            name='company_id',
            field=models.CharField(default='9a1eee73', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='61fb107b', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='hsn_user_id',
            field=models.CharField(default='b28e8e45', max_length=150),
        ),
    ]
