# Generated by Django 3.1.6 on 2021-03-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_auto_20210301_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='barcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compony',
            name='company_id',
            field=models.CharField(default='822f8295', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='463672ed', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='hsn_user_id',
            field=models.CharField(default='3d9068c4', max_length=150),
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.CharField(default='b8cd4305', max_length=100),
        ),
        migrations.AlterField(
            model_name='units',
            name='short_name',
            field=models.CharField(default='c5433ef9', max_length=100),
        ),
    ]
