# Generated by Django 3.1.6 on 2021-03-05 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_auto_20210305_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compony',
            name='company_id',
            field=models.CharField(default='8fc496cf', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='64ef145d', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='hsn_user_id',
            field=models.CharField(default='d929a9f4', max_length=150),
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.CharField(default='c4d5d775', max_length=100),
        ),
        migrations.AlterField(
            model_name='units',
            name='short_name',
            field=models.CharField(default='1da82ab0', max_length=100),
        ),
        migrations.AlterField(
            model_name='units',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
