# Generated by Django 3.1.6 on 2021-03-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_auto_20210305_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permissions',
            field=models.JSONField(default={'type': 'cxcv'}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compony',
            name='company_id',
            field=models.CharField(default='eef58683', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='29a14796', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='hsn_user_id',
            field=models.CharField(default='a695c42a', max_length=150),
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.CharField(default='cfa09c87', max_length=100),
        ),
        migrations.AlterField(
            model_name='units',
            name='short_name',
            field=models.CharField(default='3f292c5f', max_length=100),
        ),
    ]
