# Generated by Django 3.1.6 on 2021-03-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_auto_20210317_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivary_approved_date',
            new_name='delivery_approved_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivary_date',
            new_name='delivery_date',
        ),
        migrations.AlterField(
            model_name='compony',
            name='company_id',
            field=models.CharField(default='d33067fb', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='904c33fe', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='hsn_user_id',
            field=models.CharField(default='d3850b1b', max_length=150),
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.CharField(default='398a00d4', max_length=100),
        ),
        migrations.AlterField(
            model_name='units',
            name='short_name',
            field=models.CharField(default='25aed946', max_length=100),
        ),
    ]
