# Generated by Django 3.1.6 on 2021-03-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0024_auto_20210317_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compony',
            name='company_id',
            field=models.CharField(default='f39f62c8', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(default='dc712d45', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='hsn_user_id',
            field=models.CharField(default='93c1c38b', max_length=150),
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.CharField(default='c5edf99b', max_length=100),
        ),
        migrations.AlterField(
            model_name='units',
            name='short_name',
            field=models.CharField(default='5845d44e', max_length=100),
        ),
    ]
